apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alpine
resources:
- ../base
images:
  - name: alpine
    newName: thepwagner/alpine:3.14.1@sha256:be9bdc0ef8e96dbc428dc189b31e2e3b05523d96d12ed627c37aa2936653258c
