apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alpine
resources:
- ../base
images:
  - name: alpine
    newName: jitesoft/alpine
    digest: sha256:006cbbbaefe2a57fefbba615ee97e1c29289a31d6e52ae12b79d2e0314794bca
