apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alpine
resources:
- ../base
images:
  - name: alpine
    newTag: 3.14.1@sha256:eb3e4e175ba6d212ba1d6e04fc0782916c08e1c9d7b45892e9796141b1d379ae
