apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alpine
resources:
- ../base
images:
  - name: alpine
    newTag: 3.14.0@sha256:adab3844f497ab9171f070d4cae4114b5aec565ac772e2f2579405b78be67c96
